### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Cyborgdelta1** [MrBrit-TCAdmin-Game-Configs/TCAdmin-v2#2]
Hi Guys have an error on import for space engineers Ver 1.0

`'>' is an unexpected token. The expected token is '='. Line 42, position 91.`

**Comment by numpty9989** [comment]
Which config is that with??

**Comment by Cyborgdelta1** [comment]
The one Brit just uploaded 

https://github.com/MrBrit-TCAdmin-Game-Configs/TCAdmin-v2/blob/master/Space-Engineers-Windows/se-win%20-%20Windows.xml

**Comment by numpty9989** [comment]
I will upload to my tcadmin and try to reproduce the error

**Comment by Cyborgdelta1** [comment]
If it helps I am using ver 2.0.109.0

**Comment by numpty9989** [comment]
i have just tried the config you linked it imported perfectly fine for me

**Comment by Cyborgdelta1** [comment]
Hi Brit found the issue it was a config ID clash 
http://clientforums.tcadmin.com/showpost.php?p=77286&postcount=90
